#
# loadfasta by Stephen Cohen <cohen.1107@osu.edu>
# Released under CC0 1.0 Universal - see LICENSE
#

 TARGET=example
CC?=cc
CFLAGS=-Wall -Wextra -Wpedantic
CFILES=example.c ../loadfasta.c
default:
	$(CC) -o $(TARGET) $(CFILES) $(CFLAGS)
all: default
